### ISSUE TITLE
Error: No PostCSS config found

### ISSUE THREAD

**Issue by scottgallant** [forestryio/create-static-site#45] opened 2018-04-28 01:34 UTC
After running npm start I'm getting a Gulp Post CSS error:

```
[22:31:19] [PostCSS] Error in plugin 'gulp-postcss'
[22:31:19]           Message:
[22:31:19]               No PostCSS Config found in: /Users/scott/Documents/projects/forestry-local/create-static-site/forestry-qa
[22:31:19]           Details:
[22:31:19]               fileName: /Users/scott/Documents/projects/forestry-local/create-static-site/forestry-qa/src/css/styles.css
[22:31:19]           Stack:
[22:31:19]           Error: No PostCSS Config found in: /Users/scott/Documents/projects/forestry-local/create-static-site/forestry-qa
[22:31:19]               at /Users/scott/Documents/projects/forestry-local/create-static-site/forestry-qa/node_modules/postcss-load-config/index.js:51:26
[22:31:19]               at <anonymous>
```

**Comment by bzerangue** [comment] 2018-04-28 17:34
Looks like this is related to issue #44.

**Comment by stoqe** [comment] 2018-04-30 13:03
Is this breaking Create Static Site at the moment? npm start serves http://localhost:3000/ but then if I navigate to the blog post example it breaks the page and closes the connection.

**Comment by ncphillips** [comment] 2018-04-30 13:50
Duplicate of #44

**Closed by ncphillips** 2018-04-30 13:50 UTC
